Sprint 05
KsuPers/MovieQuiz-ios pull request #3
Opened 2022-10-20 15:40 UTC by KsuPers

2022-10-20 16:57 UTC, mmbabaev requested changes

2022-10-20 16:57 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        statisticService = StatisticServiceImplementation()
тут это не имеет значения, но не рекомендую что-то делать до `super.viewDidLoad()`

2022-10-20 16:57 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        if isEnabled{
лучше использовать свойство кнопок enabled

При начале ожидания "выключать" кнопку, после ожидания "включать" https://developer.apple.com/documentation/uikit/uicontrol/1618217-isenabled

2022-10-20 16:57 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            let text = "Ваш результат: \(correctAnswers) из \(questionsAmount)\nКоличество сыгранных квизов: \(statisticService.gamesCount)\nРекорд: \(statisticService.bestGame.correct)/\(statisticSe
получилась ограмная строка. Можно использовать тройные кавычки `"""`

2022-10-20 16:57 UTC, mmbabaev commented on MovieQuiz/Services/StatisticServiceImplementation.swift
> +    private var total: Int {
хорошо сделано

2022-10-20 16:57 UTC, mmbabaev commented
![Screen Shot 2022-10-20 at 19 57 02](https://user-images.githubusercontent.com/12600807/197011764-5b6727ee-e079-4d4a-ac14-bf8817b7bc85.png)
уберите warning

2022-10-20 17:11 UTC, mmbabaev requested changes

2022-10-20 17:11 UTC, mmbabaev commented on MovieQuiz/Resources/Assets.xcassets/Images/image 2/Defolt.imageset/Contents.json
> +{
Этот ассет не используется

2022-10-21 18:58 UTC, KsuPers commented
> 
Убирала warning про ассеты через удаление этой штуки. 

<img width="932" alt="снимок_экрана" src="https://user-images.githubusercontent.com/91607076/197269162-2e60c9df-8b9d-4a83-8cd5-64a4893caa05.png">

Картинки с восклицательным знаком нет. Я могу как-то по-другому сделать так, чтобы предупреждение не вылезало у тех, кто скачивает код?

2022-10-28 02:50 UTC, merged